version: '3'

services:
       
  postgres:
    image: postgres:14.4-alpine
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
    restart: on-failure
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
      POSTGRES_DB: keycloak
      POSTGRES_HOST: postgres

  keycloak:
    build: keycloak
    depends_on:
       - postgres
    restart: on-failure
    ports:
       - 8443:8443
    environment:
       # DB access
       - KC_DB=postgres
       - KC_DB_URL=jdbc:postgresql://postgres/keycloak
       - KC_DB_USERNAME=keycloak
       - KC_DB_PASSWORD=password
       # hostname
       - KC_HOSTNAME=localhost
       - KC_HOSTNAME_STRICT_HTTPS=true
       # default admin user
       - KEYCLOAK_ADMIN=admin
       - KEYCLOAK_ADMIN_PASSWORD=Pa55w0rd
    command:
       - "start --optimized"

  app:
    container_name: dispatch-app
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./src:/dispatch/src
      - ./public:/dispatch/public

volumes:
  postgresql:
  postgresql_data:

